#!/usr/bin/env ruby
EXE=`basename #{__FILE__}`.strip
if !system("which #{EXE} 2>/dev/null >/dev/null")
  puts "#{EXE} is not in your PATH available ... add it with:\n\texport PATH=$PATH:#{`readlink -f $(dirname #{__FILE__})`}\n"
  exit 1
end

require 'rubygems'
require 'json'
require 'pp'

#CURRENT_RECIPE=`ls -1 /root/scalarium-agent/log/chef/*.json | tail -n 1`.strip
CURRENT_RECIPE="/tmp/foo.json"
TMP_RECIPE_PATH="/tmp"
TMP_UPDATE_RECIPES_PATH="/tmp/site-cookbooks"
CHEF_EXECUTABLE="/root/scalarium-agent/bin/chef-solo -c /root/scalarium-agent/config/solo.rb -j" 
SITE_COOKBOOKS_DIR="/root/scalarium-agent/site-cookbooks"

config_data = JSON.load(File.read(CURRENT_RECIPE))



if ARGV.size == 0 || ARGV[0] == "help" 
  puts <<EOF



Usage: #{EXE} command
  
  commands:
    sc              show current configuration
    rl              list the chef recipes of the current config
    uc              update custom cookbooks
    exec            execute all recipes of the current role
    exec <recipes>  only execute the specified recipes (separate by comma without blanks)  



EOF

elsif ARGV[0] == "sc"
  pp config_data
elsif ARGV[0] == "rl"
  puts "recipes:"
  puts 
  puts "\t#{config_data["recipes"].join("\n\t")}"
  puts 

  puts "custom recipes:"
  puts 
  puts "\t#{config_data["scalarium_custom_cookbooks"]["recipes"] ? config_data["scalarium_custom_cookbooks"]["recipes"].join("\n\t") : "\tnone"}"
elsif ARGV[0] == "ur"
  custom_cookbooks_url = config_data["scalarium_custom_cookbooks"]["scm"]["repository"]
  if !custom_cookbooks_url
    puts "the current configuration does not seem to have custom recipes"
    exit 2
  end
  if config_data["scalarium_custom_cookbooks"]["scm"]["type"] != "git"
    puts "only git repositories are supported at the moment"
    exit 3
  end
  if  config_data["scalarium_custom_cookbooks"]["scm"]["ssh_key"].empty? ||
      config_data["scalarium_custom_cookbooks"]["scm"]["username"].empty? ||
      config_data["scalarium_custom_cookbooks"]["scm"]["password"].empty?
    puts "only public repos are supported at the moment"
    exit 4
  end

  system("mkdir -p #{TMP_UPDATE_RECIPES_PATH}; cd #{TMP_UPDATE_RECIPES_PATH}; git clone --bare #{custom_cookbooks_url}; mv #{SITE_COOKBOOKS_DIR} #{SITE_COOKBOOKS_DIR}.bak; mv *.git #{SITE_COOKBOOKS_DIR}; rm -rf #{TMP_UPDATE_RECIPES_PATH}")

elsif ARGV[0] == "exec"
  if ARGV.size == 1
    command = "#{CHEF_EXECUTABLE} #{CURRENT_RECIPE}"

    puts "executing current chef config:"
    puts "\t#{command}\n\n"

    system(command)
    puts "\n\n\n\n\n************************************** finished executing command:\n\t#{command}\n\n"
  else
    recipes = ARGV[1].split(",")
    tmp_recipe = "#{TMP_RECIPE_PATH}/chef_config__#{ARGV[1].gsub("::", "-").gsub(",", "__")}.json"
    
    config_data["recipes"] = config_data["recipes"].select{|x| recipes.include?(x)}
    config_data["scalarium_custom_cookbooks"]["recipes"] = config_data["scalarium_custom_cookbooks"]["recipes"].select{|x| recipes.include?(x)}

    if not config_data["scalarium_custom_cookbooks"].empty?
      config_data["recipes"] << "scalarium_custom_cookbooks::load"
      config_data["recipes"] << "scalarium_custom_cookbooks::execute"
    end

    f = File.open(tmp_recipe, "w")
    f << config_data.to_json
    f.close

    command = "#{CHEF_EXECUTABLE} #{tmp_recipe}"
    puts "executing temporary chef config:"
    puts "\t#{command}\n\n"

    system(command)
    puts "\n\n\n\n\n************************************** finished executing command:\n\t#{command}\n\n"
  end
end
